DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS accounts;

DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS clusters;
DROP TABLE IF EXISTS modules;
DROP TABLE IF EXISTS applications;