// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: cluster.sql

package db

import (
	"context"
	"database/sql"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO cluster (
  cluster_name,
  cluster_id,
  provider,
  k8s_version,
  url
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, cluster_name, cluster_id, provider, k8s_version, url, created_at
`

type CreateClusterParams struct {
	ClusterName string         `json:"cluster_name"`
	ClusterID   string         `json:"cluster_id"`
	Provider    sql.NullString `json:"provider"`
	K8sVersion  sql.NullString `json:"k8s_version"`
	Url         sql.NullString `json:"url"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRowContext(ctx, createCluster,
		arg.ClusterName,
		arg.ClusterID,
		arg.Provider,
		arg.K8sVersion,
		arg.Url,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.ClusterName,
		&i.ClusterID,
		&i.Provider,
		&i.K8sVersion,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}
