// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Application struct {
	ID        int64          `json:"id"`
	Provider  sql.NullString `json:"provider"`
	AppName   string         `json:"app_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Cluster struct {
	ID          int64          `json:"id"`
	ClusterName string         `json:"cluster_name"`
	ClusterID   string         `json:"cluster_id"`
	Provider    sql.NullString `json:"provider"`
	K8sVersion  sql.NullString `json:"k8s_version"`
	Url         sql.NullString `json:"url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Module struct {
	ID         int64          `json:"id"`
	Provider   sql.NullString `json:"provider"`
	ModuleName string         `json:"module_name"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Project struct {
	ID          int64          `json:"id"`
	ProjectName string         `json:"project_name"`
	ProjectID   string         `json:"project_id"`
	ClusterID   string         `json:"cluster_id"`
	Url         sql.NullString `json:"url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
